### ISSUE TITLE
Time for a new release.

### ISSUE THREAD

**Issue by hemanth** [tj/git-extras#407]
@nicolaiskogheim @spacewander you guys want to do a quick round of testing?

**Comment by nicolaiskogheim** [comment]
I have done some testing, almost done with looking through the files that have been changed since the previous release.  

Here is my progress (list generated with `git diff --name-only 3.0.0..master`
```shell
√ Commands.md
√ Installation.md
√ Makefile
√ Makefile.msys
√ bin/git-alias
√ bin/git-archive-file
√ bin/git-changelog
√ bin/git-contrib
√ bin/git-effort
√ bin/git-extras
√ bin/git-fork
√ bin/git-graft
√ bin/git-guilt
√ bin/git-ignore
√ bin/git-line-summary
bin/git-merge-into
etc/bash_completion.sh
install.cmd
install.sh
man/git-alias.md
man/git-contrib.md
man/git-effort.md
man/git-extras.md
man/git-fork.md
man/git-graft.md
man/git-guilt.md
man/git-line-summary.md
man/git-summary.md
man/index.txt
```

**Comment by spacewander** [comment]
:+1: 
I will run them on Linux this weekend.

**Comment by spacewander** [comment]
The test of Linux part has been done.
Maybe I can do a test with msysgit? I have got access to a Windows computer recently.

**Comment by hemanth** [comment]
Nice! Go ahead please. We shall wait.

**Comment by spacewander** [comment]
I am testing with msysgit, maybe it can be done in this week.

**Comment by spacewander** [comment]
Tested on windows slightly.

| command | status | failure reason |
|----|----| ---- |
|scp|✗|problem with basename |
|fork|✗| problem of curl implementation |
|fresh-branch|✗| break not accepted in case block |
|reset-file|✗| further debug required |
|obliterate|✗| further debug required |
|authors|✗| further debug required |
|changelog|✗| further debug required |
|extras|√||
|squash|√||
|summary|√||
|effort|√||
|commits-since|√||
|count|√||
|create-branch|√||
|delete-branch|√||
|delete-submodule|√||
|delete-tag|√||
|delete-merged-branches|√||
|guilt|√||
|merge-int|√||
|graft|√||
|alias|√||
|ignore|√||
|info|√||
|release|√||
|contrib|√||
|repl|√||
|undo|√||
|gh-pages|√||
|setup|√||
|touch|√||
|feature|√||
|refactor|√||
|bug|√||
|chore|√||
|local-commits|√||
|archive-file|√||
|missing|√||
|lock|√||
|locked|√||
|unlock|√||
|pr|√||
|root|√||
|delta|√||
|merge-repo|√||
|psykorebase|√||

We can make sure that **most** of commands from `git-extras` run well on windows. It is an unexpected good news!

**Comment by hemanth** [comment]
Lets do a new version! Or is anyone interested to fix those windows bugs?

**Comment by nicolaiskogheim** [comment]
I just ran `git fresh-branch` and it totally destroyed my HEAD. I want to look at that, and get rid of the `break` statement first.

**Comment by hemanth** [comment]
:cactus: Alright!

**Comment by nwinkler** [comment]
Any update on this? Looking forward to an updated release, and an updated version on Homebrew (see #387)

**Comment by hemanth** [comment]
We need to update `brew` as well.

**Comment by raido** [comment]
v3.0.0 has some errors on OS X 10.10.5, git-effort for example. Master runs fine, i just took me some time to figure out, that i should simply checkout master && make install.

Looking forward to new release.

**Comment by nicolaiskogheim** [comment]
Before we release, I want to change some things in `git effort`. The kind of things that is a good idea to do before we release. I will come back to you this weekend.

**Comment by hemanth** [comment]
We can wait.

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by qw3rtman** [comment]
Any movement on the changes to `git effort` @nicolaiskogheim? If not, I think it's best to focus on that after a release (unless there are currently bugs in `git effort`). It's been a while (and **208 commits**) since we bumped the version (and updated on Homebrew; see #461). I think our best option is to bump version to `4.0.0` as soon as possible. Thoughts?

**Comment by hemanth** [comment]
I would also vote for bumping the version.

**Comment by spacewander** [comment]
I can't wait for a new release!

**Comment by qw3rtman** [comment]
Just made a new issue for the new release with all the changes since the body was quite lengthy. See #487.

**Comment by nicolaiskogheim** [comment]
@qw3rtman Hey, sorry, I forgot about this issue here. Yes, everything I wanted to do in regards to `git-effort` is already merged a long time ago.

**Comment by qw3rtman** [comment]
No worries, @nicolaiskogheim! :smile:
