### ISSUE TITLE
git-release: does not work for me

### ISSUE THREAD

**Issue by perlun** [tj/git-extras#696]
Here is what it says:

```
$ git release 0.3.1
... releasing 0.3.1
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

No tag is generated, no changes are pushed. Any ideas on how to debug this?

Some more details:

```
$ git tag -l
0.1.0
0.1.1
0.2.0
0.3.0
$ git --version
git version 2.15.1
$ uname -a
Darwin ecvaawplun6.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin
```

**Comment by spacewander** [comment]
@perlun 
If my guess is right, the pr #697 could fix the problem.

`git release` will create a new commit with `Release blahblah` as commit message. If there is nothing to commit, it will break in the middle. Therefore, I add `--allow-empty` option to `git commit` command, so that an empty commit could be created on this occasion.

**Comment by perlun** [comment]
> If my guess is right, the pr #697 could fix the problem.

Your guess is right - for another repo, where I had a dirty file, it worked as it should.
