### ISSUE TITLE
completion for zsh

### ISSUE THREAD

**Issue by moonrumble** [tj/git-extras#70]
If some one has configured zsh completion please provide.

**Comment by GuillaumeSeren** [comment]
Hey there,
I also use zsh with oh-my-zsh (with antigen),
and I find at least 1 other command without completion (git missing).

It is funny because all that was working out of the box with bash so I will push forward to see if I can that.

Guillaume.

**Comment by GuillaumeSeren** [comment]
Ok I just find that  the completion plugin of oh-my-zsh is old last commit 3 years ago, I will check that completion working for *new* functions.

**Comment by GuillaumeSeren** [comment]
Hello,
after searching on this subject I ending in upgrading the zsh completion file for git-extras,
but just in case, somebody find a better way than me I left a sum of information I get:
* Zsh use a different completion system, and did not use a '/etc/bash_completion.d/' directory, the user have to give a zsh completion to load OR try the bash support (which is not working on my setup, and discouraged by the doc).
* The process to try to use the bash's completion file is here: http://zshwiki.org/home/convert/bash
* I didn't success to use my bash's completion file on zsh, but as it is written in the wiki (and it is old): " Keep in mind that it is much better to rewrite completion functions for zsh than to spend much time getting a bash function to work with this. "

So as I can not be sure due to the time and even if can work, it will be a clunky hack so I decide to upgrade the existing zsh's completion file for git-extra (last commit 3 years ago), but I think the completion file should be in the upstream tree, as you can see in the git tree here: https://github.com/git/git/tree/master/contrib/completion

I will reply here as I get it done, feel free to send me informations if have worked on that area.

Guillaume.

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Hyderabad go to  
http://www.expert5th.in/packers-and-movers-hyderabad/
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Gurgaon go to 
http://www.expert5th.in/packers-and-movers-gurgaon/
For Expert 5 Packers and Movers Delhi go to 
http://www.expert5th.in/packers-and-movers-delhi/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Chennai go to 
http://www.expert5th.in/packers-and-movers-chennai/
For Expert 5 Packers and Movers Noida go to 
http://www.expert5th.in/packers-and-movers-noida/
For Expert 5 Packers and Movers Thane go to 
http://www.expert5th.in/packers-and-movers-thane/
For Expert 5 Packers and Movers Navi Mumbai go to 
http://www.expert5th.in/packers-and-movers-navimumbai/
For Expert 5 Packers and Movers Ghaziabad go to 
http://www.expert5th.in/packers-and-movers-ghaziabad/
For Expert 5 Packers and Movers Faridabad go to 
http://www.expert5th.in/packers-and-movers-faridabad/

**Comment by raviranjananalist** [comment]
For Expert 5 Packers and Movers Bangalore go to 
http://www.expert5th.in/packers-and-movers-bangalore/
For Expert 5 Packers and Movers Pune go to  
http://www.expert5th.in/packers-and-movers-pune/
For Expert 5 Packers and Movers Mumbai go to 
http://www.expert5th.in/packers-and-movers-mumbai/
