### ISSUE TITLE
Feature request: git pr to checkout merge commit instead of HEAD

### ISSUE THREAD

**Issue by gormac** [tj/git-extras#757]
I'd like `git pr 9999 [upstream]` to (optionally) checkout a merge commit against the branch the pull request is targeting rather than checking out HEAD. This allows me to locally test the actual result of the pull request.

**Comment by spacewander** [comment]
Do you mean checking out the merge commit created by merging the pull request into the current branch?
Could you submit a pull request to update the documentation, so that we could understand how this new feature should work?

BTW, I am too busy in the upcoming weeks. Please forgive me if I don't reply in time.

**Comment by gormac** [comment]
Similar to checking out HEAD my local git alias for checking out the merge commit to the target branch is:

`git fetch -fu upstream refs/pull/$id/merge:pr/$id && git checkout pr/$id`

So, `head` becomes `merge` and that's it. Changing it would be a breaking change though, so maybe it could just be a new command complementary to `git pr`. Something like:

`git prm 9999 [upstream]`

**Comment by spacewander** [comment]
@gormac 
Can you check if the #762 works for you? You can install the latest git-extras via source: https://github.com/tj/git-extras/blob/master/Installation.md#building-from-source
