### ISSUE TITLE
Change the default branch of this repo from master to main?

### ISSUE THREAD

**Issue by spacewander** [tj/git-extras#950]
@tfendin suggests that we can switch the default branch of this repo from master to main: https://github.com/tj/git-extras/pull/946#issuecomment-1003358562

@tj @hemanth 
What do you think about this?

**Comment by hemanth** [comment]
Given that GH has made it easy to make that change, it would be a 👍 from me 🤓

**Comment by ldo** [comment]
As somebody with a Masters degree, I wonder what the point of this is ...

**Comment by hyperupcall** [comment]
It seems [this](https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main) and [this](https://github.com/github/renaming) page has some more information on how to do it without breaking things.

As someone who has been contributing to this repository for a while, this change is very welcome. Besides improving the terminology to be more inclusive, changing to `main` brings us more in line with the rest of the developer evosystem and makes it much less inconvenient to make changes - since the proliferation of `main`, most people's muscle memory, and many people's git aliases, etc. are based off of `main`.
 
@spacewander What do you think about revisiting this? The existing consensus seems to suggest a switch would be satisfactory

**Comment by spacewander** [comment]
@tj 
Would you help to change the default branch of this project?
We don't have access to this project's setting.

**Comment by spacewander** [comment]
After discussing with @tj via email these days, we have finally changed the default branch to main. I have submitted a PR to adapt this change: https://github.com/tj/git-extras/pull/1092

**Comment by hyperupcall** [comment]
great!
